version: '3.8'

services:
  app:
    build: .
    container_name: my-nest-app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             node dist/main.js"
